### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Plabick** [JuppOtto/Google-Cardboard#2]
I added this script to my cardboard app to the cardboard main, but it is not working. It shows up and the menue options show up, but when I go to run the app, it will not walk even when triggered or the threshold angle is pased. Any ideas on what is up? Do I need to import any other assets?

**Comment by DastanIqbal** [comment]
I don't know but may be this video can help I used this video to walkin in Cardboard VR.

**Comment by Plabick** [comment]
I was able to get it to work this morning and will close the ticket. Thank
you so much for designing such a great script.
