### ISSUE TITLE
Not working with GoogleVRSDK

### ISSUE THREAD

**Issue by evonyia** [JuppOtto/Google-Cardboard#3]
Hello!
This doesn't work anymore with the new googlevrsdk that replaced cardboard sdk. Seems like a few errors are found, any idea how to fix please? I am not great with C#.

Thanks
Alice

**Comment by hedgefield** [comment]
Same problem here. Google changed all their script references and prefabs around when they rebranded Cardboard to GoogleVR so there's a bunch of nullrefs.

**Comment by JuppOtto** [comment]
I created a new script for Google VR SDK: http://bit.ly/2gHnefD
